const Config = {
  SERVER_URL: process.env.NEXT_PUBLIC_SERVER_URL,
  SERVER_URL_API: process.env.NEXT_PUBLIC_SERVER_URL_API,
  HOST_URL: process.env.NEXT_PUBLIC_HOST_URL,
  HOST_API_URL: process.env.NEXT_PUBLIC_HOST_API_URL,
  CLIENT_ID: process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID,
  CLIENT_SECRET: process.env.NEXT_PUBLIC_GITHUB_CLIENT_SECRET,
  GITHUB_OAUTH_URI: process.env.NEXT_PUBLIC_GITHUB_OAUTH_URI,
  REDIRECT_URI: process.env.NEXT_PUBLIC_REDIRECT_URI,
  API_SCOPE: process.env.NEXT_PUBLIC_GITHUB_SCOPE,
  REDIS_HOST: process.env.NEXT_PUBLIC_REDIS_HOST,
  REDIS_PORT: process.env.NEXT_PUBLIC_REDIS_PORT,
  REDIS_USERNAME: process.env.NEXT_PUBLIC_REDIS_USERNAME,
  REDIS_PASSWORD: process.env.NEXT_PUBLIC_REDIS_PASSWORD,
};

export default Config;
